# Generated by Django 3.1.4 on 2020-12-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
