# Generated by Django 3.0.6 on 2020-06-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('myuser_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ban_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('birth', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('ban_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('pay', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('store_content', models.TextField()),
                ('job_type', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='image')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=15)),
                ('birth', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('resume_content', models.TextField()),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MyUser')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_user_id', models.CharField(max_length=15)),
                ('report_content', models.TextField()),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MyUser')),
            ],
        ),
    ]
