# Generated by Django 3.0.6 on 2020-06-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='photo',
        ),
    ]
